### ISSUE TITLE
The v0.9.21 version image cannot create containers.

### ISSUE THREAD

**Issue by mwnu** [etkecc/postmoogle#10]
displaying the error: 
> docker run  ... ghcr.io/etkecc/postmoogle:latest
> docker: Error response from daemon: unable to find user app: no matching entries in passwd file.

Whether using `docker pull ghcr.io/etkecc/postmoogle:latest` or `docker build`, the image has errors.

**Comment by aine-etke** [comment]
When you run postmoogle via docker, you need to provide UID/GID via `--user` arg, e.g:

`docker run --user 1000:1000 ghcr.io/etkecc/postmoogle`

Note that if you use MDAD playbook, that's done automatically.
