### ISSUE TITLE
can you correct the link in bio ?

### ISSUE THREAD

**Issue by whoamitty** [etkecc/postmoogle#12]
There is the good link found [on matrix](https://matrix.org/ecosystem/bridges/email/) :
https://matrix.to/#/#postmoogle:etke.cc

And the bad link in the bio of the repo,
the colon is replaced by a dot :
https://matrix.to/#/#postmoogle.etke.cc

**Comment by aine-etke** [comment]
Oh, thank you for noticing!
Fixed
